# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Cache dependencies"
        uses: "actions/cache@v4"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-"

      - name: "Install highest dependencies"
        run: "composer update --prefer-dist --no-interaction --no-progress --no-suggest"

      - name: "Code Style"
        run: "vendor/bin/phpcs"

      - name: "Static Analysis"
        run: "vendor/bin/phpstan analyze"

      - name: "Rector"
        run: "vendor/bin/rector --dry-run"

      - name: "Tests"
        run: "vendor/bin/phpunit"
